// <copyright file="TeardownFeature.cs" company="xBehave.net contributors">
//  Copyright (c) xBehave.net contributors. All rights reserved.
// </copyright>

#if NET40 || NET45
namespace Xbehave.Test.Acceptance
{
    using System;
#if !V2
    using System.Globalization;
#endif
    using System.IO;
    using System.Linq;
    using System.Threading;
    using FluentAssertions;
    using Xbehave.Test.Acceptance.Infrastructure;

    // In order to release allocated resources
    // As a developer
    // I want to execute teardown actions after a scenario has run
    public static class TeardownFeature
    {
        [Background]
        public static void Background()
        {
            "Given no temporary files exist"
                .f(() =>
                {
                    foreach (var path in Directory.EnumerateFiles(Directory.GetCurrentDirectory(), "*.temp"))
                    {
                        File.Delete(path);
                    }
                });
        }

        [Scenario]
        public static void RegisteringManyTeardownsInASingleStep(Type feature, Result[] results)
        {
            "Given a step which registers many teardowns"
                .f(() => feature = typeof(SingleStep));

            "When running the scenario"
                .f(() => results = feature.RunScenarios());

            "Then there should be two results"
                .f(() => results.Length.Should().Be(2));

            "And there should be no failures"
                .f(() => results.Should().ContainItemsAssignableTo<Pass>());

            "And the first result should be generated by the step"
                .f(() => results[0].ShouldNotBeATeardown());

            "And the second result should be generated by the teardown"
                .f(() => results[1].ShouldBeATeardown());

            "Ann the teardown actions should have been executed once in reverse order after the step"
                .f(() => ShouldBeWrittenInOrder("step.1.temp", "teardown.3.temp", "teardown.2.temp", "teardown.1.temp"));
        }

        [Scenario]
        public static void RegisteringTeardownActionsWhichThrowExceptionsWhenExecuted(Type feature, Result[] results)
        {
            "Given a step which registers three teardown actions which throw exceptions when executed"
                .f(() => feature = typeof(SingleStepWithThreeBadTeardowns));

            "When running the scenario"
                .f(() => results = feature.RunScenarios());

            "Then there should be two results"
                .f(() => results.Length.Should().Be(2));

            "And the first result should be a pass"
                .f(() => results[0].Should().BeOfType<Pass>());

            "And the second result should be a failure"
                .f(() => results[1].Should().BeOfType<Fail>());

            "Then the teardown actions should have been executed once in reverse order after the step"
                .f(() => ShouldBeWrittenInOrder("step.1.temp", "teardown.3.temp", "teardown.2.temp", "teardown.1.temp"));
        }

        [Scenario]
        public static void RegisteringManyTeardownActionsInManySteps(Type feature, Result[] results)
        {
            "Given two steps with three teardowns each"
                .Given(() => feature = typeof(TwoStepsWithThreeTeardownsEach));

            "When running the scenario"
                .When(() => results = feature.RunScenarios());

            "Then there should be four results"
                .f(() => results.Length.Should().Be(3));

            "And there should be no failures"
                .f(() => results.Should().ContainItemsAssignableTo<Pass>());

            "And the teardown actions should have been executed once in reverse order after the steps"
                .f(() => ShouldBeWrittenInOrder(
                    "step.1.temp",
                    "step.2.temp",
                    "teardown.6.temp",
                    "teardown.5.temp",
                    "teardown.4.temp",
                    "teardown.3.temp",
                    "teardown.2.temp",
                    "teardown.1.temp"));
        }

#if !V2
        [Scenario]
        public static void RegisteringATeardownInManyContexts(Type feature, Result[] results)
        {
            "Given a scenario with a step which registers a teardown action followed by steps which generate two contexts"
                .f(() => feature = typeof(SingleStepTwoContexts));

            "When running the scenario"
                .f(() => results = feature.RunScenarios());

            "Then there should be no failures"
                .f(() => results.Should().ContainItemsAssignableTo<Pass>());

            "And the teardown action should have been executed once after each context"
                .f(() => ShouldBeWrittenInOrder(
                    "step.1.1.temp",
                    "step.1.2.temp",
                    "step.1.3.temp",
                    "teardown.1.1.temp",
                    "step.2.1.temp",
                    "step.2.2.temp",
                    "step.2.4.temp",
                    "teardown.2.1.temp"));
        }
#endif

        [Scenario]
        public static void FailingSteps(Type feature, Result[] results)
        {
            "Given two steps with teardowns followed by a failing step"
                .Given(() => feature = typeof(TwoStepsWithTeardownsFollowedByAFailingStep));

            "When running the scenario"
                .When(() => results = feature.RunScenarios());

            "Then there should be one failure"
                .Then(() => results.OfType<Fail>().Count().Should().Be(1));

            "And the teardown actions should have been executed once after each step"
                .f(() => ShouldBeWrittenInOrder(
                    "step.1.temp",
                    "step.2.temp",
                    "step.3.temp",
                    "teardown.2.temp",
                    "teardown.1.temp"));
        }

        [Scenario]
        public static void FailureToCompleteAStep(Type feature, Result[] results)
        {
            "Given a failing step with three teardowns"
                .Given(() => feature = typeof(FailingStepWithThreeTeardowns));

            "When running the scenario"
                .When(() => results = feature.RunScenarios());

            "Then there should be one failure"
                .Then(() => results.OfType<Fail>().Count().Should().Be(1));

            "And the teardown actions should have been executed once in reverse order after the step"
                .f(() => ShouldBeWrittenInOrder(
                    "step.1.temp",
                    "teardown.3.temp",
                    "teardown.2.temp",
                    "teardown.1.temp"));
        }

        private static void ShouldBeWrittenInOrder(params string[] paths)
        {
            var writings = paths.Select(s => new { Path = s, Ticks = Read(s) }).ToArray();
            writings.Should().Equal(writings.OrderBy(writing => writing.Ticks));
        }

        private static AndConstraint<FluentAssertions.Primitives.StringAssertions> ShouldNotBeATeardown(this Result result)
        {
            return result.DisplayName.Should().NotContainEquivalentOf("(teardown)");
        }

        private static AndConstraint<FluentAssertions.Primitives.StringAssertions> ShouldBeATeardown(this Result result)
        {
            return result.DisplayName.Should().ContainEquivalentOf("(teardown)");
        }

        private static void Write(string path)
        {
            Thread.Sleep(1);
            using (var file = new StreamWriter(path, false))
            {
                file.Write(DateTime.Now.Ticks);
            }
        }

        private static long Read(string path)
        {
            return long.Parse(File.ReadAllText(path));
        }

        private static class SingleStep
        {
            [Scenario]
            public static void Scenario()
            {
                "Given something"
                    .Given(() => Write("step.1.temp"))
                    .Teardown(() => Write("teardown.1.temp"))
                    .Teardown(() => Write("teardown.2.temp"))
                    .Teardown(() => Write("teardown.3.temp"));
            }
        }

        private static class SingleStepWithThreeBadTeardowns
        {
            [Scenario]
            public static void Scenario()
            {
                "Given something"
                    .Given(() => Write("step.1.temp"))
                    .Teardown(() =>
                    {
                        Write("teardown.1.temp");
                        throw new InvalidOperationException();
                    })
                    .And()
                    .Teardown(() =>
                    {
                        Write("teardown.2.temp");
                        throw new InvalidOperationException();
                    })
                    .And()
                    .Teardown(() =>
                    {
                        Write("teardown.3.temp");
                        throw new InvalidOperationException();
                    });
            }
        }

        private static class TwoStepsWithThreeTeardownsEach
        {
            [Scenario]
            public static void Scenario()
            {
                "Given something"
                    .Given(() => Write("step.1.temp"))
                    .Teardown(() => Write("teardown.1.temp"))
                    .Teardown(() => Write("teardown.2.temp"))
                    .Teardown(() => Write("teardown.3.temp"));

                "And something else"
                    .Given(() => Write("step.2.temp"))
                    .Teardown(() => Write("teardown.4.temp"))
                    .Teardown(() => Write("teardown.5.temp"))
                    .Teardown(() => Write("teardown.6.temp"));
            }
        }

#if !V2
        private static class SingleStepTwoContexts
        {
            private static int context;

            [Scenario]
            public static void Scenario()
            {
                "Given something"
                    .Given(() =>
                    {
                        ++context;
                        Write(
                            string.Concat("step.", context.ToString(CultureInfo.InvariantCulture), ".1.temp"));
                    })
                    .Teardown(() => Write(
                        string.Concat("teardown.", context.ToString(CultureInfo.InvariantCulture), ".1.temp")));

                "When something happens"
                    .When(() => Write(
                        string.Concat("step.", context.ToString(CultureInfo.InvariantCulture), ".2.temp")));

                "Then something"
                    .Then(() => Write(
                        string.Concat("step.", context.ToString(CultureInfo.InvariantCulture), ".3.temp")))
                    .InIsolation();

                "And something"
                    .Then(() => Write(
                        string.Concat("step.", context.ToString(CultureInfo.InvariantCulture), ".4.temp")));
            }
        }
#endif

        private static class TwoStepsWithTeardownsFollowedByAFailingStep
        {
            [Scenario]
            public static void Scenario()
            {
                "Given something"
                    .Given(() => Write("step.1.temp"))
                    .Teardown(() => Write("teardown.1.temp"));

                "When something"
                    .And(() => Write("step.2.temp"))
                    .Teardown(() => Write("teardown.2.temp"));

                "Then something happens"
                    .Then(() =>
                    {
                        Write("step.3.temp");
                        1.Should().Be(0);
                    });
            }
        }

        private static class FailingStepWithThreeTeardowns
        {
            [Scenario]
            public static void Scenario()
            {
                "Given something"
                    .Given(() =>
                    {
                        Write("step.1.temp");
                        throw new InvalidOperationException();
                    })
                    .Teardown(() => Write("teardown.1.temp"))
                    .Teardown(() => Write("teardown.2.temp"))
                    .Teardown(() => Write("teardown.3.temp"));
            }
        }
    }
}
#endif
